### ISSUE TITLE
Package for Ubuntu 18.04

### ISSUE THREAD

**Issue by PeterDaveHello** [gslin/dehydrated-lite-ppa#1]
Hi @gslin,

Just asking, will this project continue to provide packages for newer Ubuntu like 18.04?

I saw the latest update on the ppa homepage was 58 weeks ago:
https://launchpad.net/~gslin/+archive/ubuntu/dehydrated

Thank for your time and ppa!

**Comment by gslin** [comment]
See https://launchpad.net/~gslin/+archive/ubuntu/dehydrated-lite this one.

**Comment by PeterDaveHello** [comment]
Didn't notice it's been a new package, thanks a lot 🙇
